### ISSUE TITLE
use nvim-treesitter module

### ISSUE THREAD

**Issue by elianiva** [JoosepAlviste/nvim-ts-context-commentstring#1]
Hi there! Thanks for making this plugin, I really like it :)
One trivial issue though, since this plugin requires `nvim-treesitter`, I think it would be better if it also uses the module template. Similar to [this plugin](https://github.com/windwp/nvim-ts-autotag/issues/1#issue-825298190). This should be trivial to add. 

https://github.com/windwp/nvim-ts-autotag/blob/5244e629d38ea0beda4805a3b08bbbe5e8ed6bf5/lua/nvim-ts-autotag.lua#L7-L14

If you agree, I can make a PR later if you want.

**Comment by JoosepAlviste** [comment]
Hey! I agree and was actually planning on doing this myself. I think that I'll have time in the next few days for this, but if you'd like to do it, then I would gladly accept a PR 😄
