### ISSUE TITLE
Required fields in ts_context_commentstring.Config

### ISSUE THREAD

**Issue by EricDriussi** [JoosepAlviste/nvim-ts-context-commentstring#116]
When following the [instructions](https://github.com/JoosepAlviste/nvim-ts-context-commentstring/wiki/Integrations#plugins-with-a-pre-comment-hook) for integrating with plugins with a pre-comment hook, I noticed my LSP complaining that `languages`, `config` and `commentary_integration` are required and missing.
Looking at the [class setup](https://github.com/JoosepAlviste/nvim-ts-context-commentstring/blob/6b5f95aa4d24f2c629a74f2c935c702b08dbde62/lua/ts_context_commentstring/config.lua#L37) they are indeed set up as required but don't actually seem to be necessary.
I'm guessing the class fields need to be updated as optional or the wiki needs to include them as well?

**Comment by JoosepAlviste** [comment]
The types were indeed not the best, unfortunately. Thanks for bringing this up!

I pushed a commit with some improvements, marking them as optional. Will close the issue but let me know if you notice any other issues with it 👍
