### ISSUE TITLE
[Feature request] disabling per filetype

### ISSUE THREAD

**Issue by seblj** [JoosepAlviste/nvim-ts-context-commentstring#13]
I would really like to disable this only in certain filetypes. The reason for this is because for example in C, I would like to be able to toggle between the two commentstrings on the go.

**Comment by JoosepAlviste** [comment]
Hey @seblj! Disabling the commentstring updating in a specific language makes a lot of sense.

One clarifying question though: would you like the plugin to be totally disabled or would you just like to disable the autocmd? If you'd like to manually call `update_commentstring`, then I could just disable the autocmd.

Also, I'm interested to hear about how the manual toggling workflow would look like for you. I'm not super familiar with C so I don't know how commenting is special there.

**Comment by seblj** [comment]
I would like the plugin to be totally disabled, because from my understanding it runs `update_commentstring` for vim-commentary even if autocmd is turned off.

In C I have had the commentstring set to `/*%s*/`, but I would like to change it to `//%s`. This doesn't really change anything in C, as you can use both of them everywhere. However, if I change to `//%s`, I know there are a few files where I still have some comments with the commentstring set to `/*%s*/`. Now vim-commentary can't uncomment those lines. I would then like to be able to switch the commentstring with something like this:

```Lua
local switch_commentstring = function(commentstrings)
    local current = vim.api.nvim_buf_get_option(0, 'commentstring')
    for _, cs in pairs(commentstrings) do
        if not current:find(cs, 1, true) then
            return cs
        end
    end
end

M.toggle_commenstring = function()
    local commentstrings = {
        c = {'//%s', '/*%s*/'}
    }
    local ft = vim.api.nvim_buf_get_option(0, 'filetype')
    if not commentstrings[ft] then return end
    local commentstring = switch_commentstring(commentstrings[ft])
    vim.api.nvim_buf_set_option(0, 'commentstring', commentstring)
    vim.api.nvim_echo({{string.format('Now using %s', commentstring)}}, false, {})
end
```

I could then add a mapping using the toggle_commentstring to toggle between those to commentstrings if I find it necessary.

**Comment by JoosepAlviste** [comment]
Good news @seblj! I found out that treesitter modules can be disabled in specific filetypes out of the box with the `disable` property. So, something like this should work:

```lua
require('nvim-treesitter.configs').setup {
  context_commentstring = {
    enable = true,
    disable = {'tsx'},
  },
}
```

Could you try it out and let me know if it works for you?

**Comment by seblj** [comment]
I was so sure that I tried that before, but I guess I didn't. Yes that works! Thanks!
