### ISSUE TITLE
Error when nvim-treesitter is added as opt package in packer

### ISSUE THREAD

**Issue by hiddenruins** [JoosepAlviste/nvim-ts-context-commentstring#15]
Hi, thanks for the awesome plugin. Neovim shows an error when `nvim-treesitter` is made an optional package in packer.nvim.

Here's the error message
![image](https://user-images.githubusercontent.com/5569621/121980570-e204d000-cdab-11eb-9849-43b9fa252716.png)

Relevant Packer config
![image](https://user-images.githubusercontent.com/5569621/121980643-05c81600-cdac-11eb-9df2-8a3d6eb77744.png)

Treesitter config
```lua
vim.cmd[[packadd nvim-treesitter]]

local ts_config = require('nvim-treesitter.configs')

ts_config.setup({
  -- ensure_installed = 'maintained',
  highlight = { enable = true },
  incremental_selection = { enable = true },
  indent = { enable = true },

  context_commentstring = { enable = true },

})

```

**Comment by JoosepAlviste** [comment]
Hey @hiddenruins! Unfortunately, I don't know too much about `opt` packages. Is it correct that the only difference is that you need to `packadd mypackage` for it to be registered/started?

Would it make sense to make `nvim-ts-context-commenstring` a dependency of `nvim-treesitter`?

```
use {
  'nvim-treesitter/nvim-treesitter',
  opt = true,
  run = ':TSUpdate',
  requires = {'JoosepAlviste/nvim-ts-context-commentstring'},
}
```

Then, Packer should make this plugin `opt` as well if I understand correctly (`transitive_opt = true, -- Make dependencies of opt plugins also opt by default` in Packer default conf) and load it when `nvim-treesitter` is loaded. Does that work for you?

I'm not sure what could be done in this plugin. Do you have any ideas?

**Comment by clason** [comment]
I think what you want is `wants` to make sure `nvim-treesitter` is loaded before `ntcc` (your plugin's name is too long :P):

```lua
use {
'JoosepAlviste/nvim-ts-context-commentstring, cmd = '...', 
wants = 'nvim-treesitter'
}
```

(Presumably you want to lazy-load this plugin (which implies `opt`, so no need to specify it), otherwise there is no point in putting this -- and `nvim-treesitter`, which is a hard requirement -- in `opt` instead of start.)

**Comment by hiddenruins** [comment]
Thank you @clason @JoosepAlviste . Adding `after="nvim-treesitter"` in `use` seemed to do the trick.
