### ISSUE TITLE
Configurations for `commentary` and `kommentary` are not working

### ISSUE THREAD

**Issue by MuhammadSawalhy** [JoosepAlviste/nvim-ts-context-commentstring#23]
I tried to make **commentary** and **kommentary** plugins work with **nvim-ts-context-commentstring** using the configs described in the README of this repo, but it seems that `commentstring` is not updated each time I use the comment plugin.
Only **nvim-comment** plugin worked, the other two plugins work when `enable_autocmd = true`

**Comment by JoosepAlviste** [comment]
Hey @MuhammadSawalhy! How exactly did you try to configure the integrations? Could you share a minimal config where I could reproduce the issue?

Here's a simple minimal config I use:

```vim
call plug#begin('~/.config/nvim/packages/')
Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
Plug 'JoosepAlviste/nvim-ts-context-commentstring'
call plug#end()

set updatetime=100  " Or some other small value (Vim default is 4000)

lua << EOF
require('nvim-treesitter.configs').setup {
  ensure_installed = 'maintained',
  highlight = {
    enable = true,
  },
  context_commentstring = {
    enable = true
  }
}
EOF
```

**Comment by MuhammadSawalhy** [comment]
**Note**: the `commentstring` is updated only when manually run this command:

```nvim
:lua require('ts_context_commentstring.internal').update_commentstring()
```

**My minimal config**

```nvim
let g:plug_home = '~/.config/nvim/plugins'
call plug#begin(plug_home)
Plug 'nvim-treesitter/nvim-treesitter', { 'do': ':TSUpdate' }
Plug 'JoosepAlviste/nvim-ts-context-commentstring'
Plug 'b3nj5m1n/kommentary'
call plug#end()

set updatetime=100  " Or some other small value (Vim default is 4000)

lua << EOF
require('nvim-treesitter.configs').setup {
  ensure_installed = 'maintained',
  highlight = {
    enable = true,
  },
  context_commentstring = {
    enable = true,
    enable_autocmd = false,
  }
}

require('kommentary.config').configure_language('default', {
  single_line_comment_string = 'auto',
  multi_line_comment_strings = 'auto',
  hook_function = function()
    require('ts_context_commentstring.internal').update_commentstring()
  end,
})
EOF
```

**Comment by MuhammadSawalhy** [comment]
I think it is not an issue with the **nvim-ts-context-commentstring** but the configurations in the README of the repo is at least need some fixes...

**Comment by JoosepAlviste** [comment]
Which language are you trying to comment in? The `hook_function` is not executed by kommentary for `default` (see https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/19#issuecomment-916334428). For now, I would configure each language separately in kommentary. It would make sense to report this issue in the kommentary repo though.

**Comment by MuhammadSawalhy** [comment]
Ok, I am happy with **nvim-comment** 😅
