### ISSUE TITLE
Handle injected languages with language tree

### ISSUE THREAD

**Issue by JoosepAlviste** [JoosepAlviste/nvim-ts-context-commentstring#3]
It seems like we could improve the logic for injected languages by using language tree to query the language for the current node. For example, if the cursor is inside an HTML node (which is injected into another language), then we could set `commentstring` to `<!-- %s -->`.

The only configuration we would need would be the commentstring for each language:

```lua
local conf = {
  css = '/* %s */',
  html = '<!-- %s -->',
  javascript = '// %s',
  -- ...
}
```

Then, injected languages should automatically work in all cases.

However, I'm not sure how JSX style comments would work since JSX isn't an injected language.

Idea from this Reddit comment: https://www.reddit.com/r/neovim/comments/md5mym/treesitter_plugin_for_dynamically_setting/gs82lbv?utm_source=share&utm_medium=web2x&context=3

**Comment by theHamsta** [comment]
You can get the current language via 
```
local parsers = require'nvim-treesitter.parsers'


  local root_lang_tree = parsers.get_parser()
  local lang_tree = root_lang_tree:language_for_range({ line, col, line, col })
  local lang = lang_tree.lang
```

there should be no need to use queries to find out where which language is injected

**Comment by JoosepAlviste** [comment]
Thanks, @theHamsta! That code snippet was enough to help me figure it out. Now, we are only operating on the injected language sub-tree.

I still had to use queries for some languages though. Mainly because JSX is not an injected language with language tree, but it is a part of the tree created by the JS/TSX parsers.

But I did manage to use language tree for most of the logic.
