### ISSUE TITLE
Set commentstring for html.handlebars

### ISSUE THREAD

**Issue by ogirginc** [JoosepAlviste/nvim-ts-context-commentstring#35]
Is there a way to set `commentstring` for the `html.handlebars` file type?

**Comment by JoosepAlviste** [comment]
Hey @ogirginc, does handlebars have a Treesitter parser? If so, you could probably configure similarly to this:

```lua
require'nvim-treesitter.configs'.setup {
  context_commentstring = {
    enable = true,
    config = {
      handlebars = '// %s'
    }
  }
}
```

How exactly do the injected comments work in handlebars?

**Comment by JoosepAlviste** [comment]
I'll close this due to inactivity, not sure what the next steps here would be without a treesitter parser.
