### ISSUE TITLE
[Feature Request] Support Astro

### ISSUE THREAD

**Issue by peterhpchen** [JoosepAlviste/nvim-ts-context-commentstring#46]
Astro is a web framework. It has its own file type `.astro`.

https://astro.build/

It can be set up by the following:

```lua
require'nvim-treesitter.configs'.setup {
  context_commentstring = {
    enable = true,
    config = {
      astro = '<!-- %s -->'
    }
  }
}
```

Can you support it by default? I would love to send a pull request for this change if you need it.

**Comment by JoosepAlviste** [comment]
Hey! Of course, will gladly accept a PR 😄
