### ISSUE TITLE
Avoid needlessly calculating commentstring

### ISSUE THREAD

**Issue by JoosepAlviste** [JoosepAlviste/nvim-ts-context-commentstring#5]
Currently, this plugin is using `CursorHold` to trigger re-calculation of `commentstring`. This causes many unnecessary calculations that we could, in theory, avoid. We could try to only trigger this logic when the user inputs the mapping for commenting (e.g., `gcc`). 

We could create our own mappings which would first update the `commentstring` and then trigger the commenting logic.

**Comment by timsofteng** [comment]
What do you think about whole new commenting plugin based on treesitter?  You could implement current plugin there. It will allow to get rid of any dependencies and current issue as well because it will depend on own mapping.
There is no-one while treesitter commenting plugin for neovim. I suppose it could be popular and pretty useful. 
What do you think about it?
Is it make sense?

**Comment by vatosarmat** [comment]
Thanks for plugin, Joosep. IMO there is no need in autocommand
```vim
function s:ConfigCommentary() abort
  function s:CommentaryImplExpr(a)
    lua require('ts_context_commentstring.internal').update_commentstring()
    if a:a == 1
      return "\<Plug>Commentary"
    else
      return "\<Plug>CommentaryLine"
    endif
  endfunction

  xmap <expr><C-_> <sid>CommentaryImplExpr(1)
  nmap <expr><C-_> <sid>CommentaryImplExpr(0)
endfunction
```

**Comment by JoosepAlviste** [comment]
That looks great! I initially had something similar in mind. Your implementation makes it look so simple 😄 

I added an option for disabling the default autocommand and added a `vim-commentary` example to the README.

Another idea I had was to add a special configuration option for `vim-commentary`, which would create the mappings automatically. Something like `vim_commentary_integration`. I don't think that it would be too difficult to maintain these integrations for multiple commenting plugins.

What do you think of this?

**Comment by cloggier** [comment]
It would be very nice if during initialisation your plugin could detect (or by configuration) and set up itself as proxy above commenting plugin.

**Comment by JoosepAlviste** [comment]
That's a nice suggestion, I went ahead and added an automatic integration with `vim-commentary`. It should be relatively straightforward to add more integrations in the future.

Currently, the `vim-commentary` default mappings are used (`gc` mappings), so if the user has custom mappings set up, then it might be a problem. I think that we could somehow detect the user's mapping to `<Plug>Commentary` and then use those keys ourselves. But I haven't tried it out yet, it can be something for the future I think.

Do you think that this issue could be closed? CC @timsofteng

**Comment by cloggier** [comment]
@JoosepAlviste 
> Let me know if you'd like a similar integration for another commenting plugin

[terrortylor/nvim-comment](https://github.com/terrortylor/nvim-comment) pretty please? :)

**Comment by vatosarmat** [comment]
> What do you think of this?

@JoosepAlviste I think you should talk to Tim Pope about a way for user to provide some form of a `commentoption`-setting callback or autocommand in `vim-commentary`. Since your plugin whole purpose is to update the one single option, it should be KISS and there is no need in its own keybindings

**Comment by jasonrhansen** [comment]
@gegoune I just submitted a PR (#21) to add instructions to integrate with [nvim-comment](https://github.com/terrortylor/nvim-comment).

**Comment by JoosepAlviste** [comment]
Thanks for the discussion everyone! I think that I'll close this issue and future integration feature requests could be their own issues.

I've thought about the `vim-commentary` integration and I also feel like being able to configure a hook like in `kommentary` and `nvim-comment` seems like a better solution than the one there is now. I'll see if I can make a PR to add that feature to `vim-commentary` but not sure when I'll have time for that.
