### ISSUE TITLE
Comments not working for TSX

### ISSUE THREAD

**Issue by jim-at-jibba** [JoosepAlviste/nvim-ts-context-commentstring#50]
Hey,

I am having trouble getting this to work with typescriptreact file types.

I have tried both Comment.nvim and mini.comment but just getting the normall `//` comments.

Mt dots are here. Any help would be much appriciated

https://github.com/jim-at-jibba/my-dots/tree/master/nvim

**Comment by DennisTheMenace780** [comment]
What did you do to get everything working? I am having the same problem with `Comment.nvim`

**Comment by jim-at-jibba** [comment]
I think it was a package/config caching issue. It started working once I had closed neovim

**Comment by DennisTheMenace780** [comment]
Very strange, I have been struggling with this all morning and just cannot get it to work no matter what I end up trying. Had to open an issue, but hoepfully it'll sort itself out too.
