### ISSUE TITLE
Block mode commenting not working with Comment.nvim

### ISSUE THREAD

**Issue by diegoulloao** [JoosepAlviste/nvim-ts-context-commentstring#52]
I added the config mentioned in the readme for `Comment.nvim`, all seems to work good except block uncommenting.

Please see the following capture:

https://user-images.githubusercontent.com/45423661/209565482-ec596a20-7f73-438b-9be2-c597e0c5a7ee.mp4

Should I add a special `post_hook` or something?

**Comment by JoosepAlviste** [comment]
Hey!

It should not be required to have anything else configured for this plugin. Here's my configuration (very minimal):

```lua
-- ... nvim-treesitter config
  context_commentstring = {
    enable = true,
    enable_autocmd = false,
  },

-- Comment.nvim config
require('Comment').setup {
  pre_hook = require('ts_context_commentstring.integrations.comment_nvim').create_pre_hook(),
}
```

Which results in:

https://user-images.githubusercontent.com/9450943/209695479-8a5e4507-c55a-4f2d-8f41-828df9866f4b.mov

Where I'm visually selecting the lines and using `gc` (and `gcj`) to comment/uncomment.

I see that one difference we have is that in my case, the commentstring is applied on each line separately, but on yours, it's applied to the start of the first line and the ending of the second line. Maybe this has something to do with it?

Could you share your exact configuration and steps to reproduce (with specific keys pressed)?

**Comment by diegoulloao** [comment]
Hey thanks for your response!
I'll do it when I have time, now trying to fix an urgent issue. I'll keep you updated on this okay?

**Comment by diegoulloao** [comment]
Hey, yes, the difference is I'm using the visual mode with the block commenter:

```lua
comment.setup({
  -- toggle mappings in normal mode
  toggler = {
    -- line comment toggle keymap
    line = "<leader>c<leader>",
  },
  -- opleader mappings in visual mode
  opleader = {
    -- multiline comment toogle keymap
    block = "<leader>c<leader>",
  },
  -- nvim-ts-context-commentstring integration
  pre_hook = context_commentstring_integration.create_pre_hook(),
})
```

So if I'm the current line I'll work as line comment, if is visual mode, as block mode (for multiple line selecting).
Maybe that can be causing my issue?

BTW, I'm using the same keybinding for comment/uncomment (toggle).

**Comment by JoosepAlviste** [comment]
Thanks for the example config! I was able to reproduce the issue with your Comment.nvim configuration.

It looks like we previously used the cursor location for calculating the `commentstring`, but we should have been using the visual selection start location. Not sure how this wasn't breaking with the default configuration 🤔 

Anyways, I set up a PR: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/pull/54 Could you try it out and see if it fixes the issue for you as well?

**Comment by diegoulloao** [comment]
Hey thank you for the quick fix! I've tested and is working for me. Also it seems isn't breaking other sort of comments 👌🏻 
✅

**Comment by JoosepAlviste** [comment]
Sweet, thanks for the bug report and the help!
