### ISSUE TITLE
Context comments are not working for tsx files

### ISSUE THREAD

**Issue by harshaln369** [JoosepAlviste/nvim-ts-context-commentstring#55]
### Problem
For tsx files context comment string are commenting jsx element as "//":

```
export const Test = () => {
  return (
    <div>
      // <h1>What's up</h1>
    </div>
  );
};
```

jsx files are working fine with context commenting:

```
export const Test = () => {
  return (
    <div>
      {/* <h1>What's up</h1> */}
    </div>
  );
};
```
I am using nvim-ts-context-commentstring with numToStr/Comment.nvim integration.

**Comment by harshaln369** [comment]
This issue was fixed after installing tsx in treesitter.

`:TSInstall tsx`

Therefore closing this issue.

**Comment by EQuimper** [comment]
@harshaln369 omg this was my issue also. For weeks I wasn't able to fix this and now this work. I think this should be add to the docs
