### ISSUE TITLE
How do I set commentstrings for c?

### ISSUE THREAD

**Issue by UtkarshVerma** [JoosepAlviste/nvim-ts-context-commentstring#60]
Would it be possible to set a commentstring for C? I use `mini.comment` with the `update_commentstring` function set up in the pre-hook. However, this does not allow me to set any commentstring through `after/ftplugin/c.vim` as this plugin overrides it whenever I do the comment.

I tried this, but it doesn't work:

```lua
        context_commentstring = {
          enable = true,
          enable_autocmd = false,
          config = {
            c = "//%s",
          },
        },
```

**Comment by JoosepAlviste** [comment]
Hey @UtkarshVerma! Do you have the C Treesitter parser installed? If you're using Treesitter in C files, then I wouldn't expect `after/plugin/c.vim` to work since this plugin should set it.

I tried this out myself by installing the C parser: `:TSInstall c` and configuring the `commentstring`:

```lua
context_commentstring = {
  enable = true,
  enable_autocmd = false,
  config = {
    c = '// test %s',
  },
},
```

Then, commenting seems to use the correct `commentstring`:

https://user-images.githubusercontent.com/9450943/231355697-51126cc2-690d-46cd-81e1-17d81782b839.mov

I'm using Comment.nvim though, but I wouldn't expect there to be any big differences from that.

To debug this further, could you show what `:=require('ts_context_commentstring.internal').calculate_commentstring()` outputs in C files?

**Comment by UtkarshVerma** [comment]
Thank you for the reply. I ran your command and got nil. I have the C parser installed for Treesitter too.

![image](https://user-images.githubusercontent.com/31820255/231379094-117d6113-4e5f-49f9-82ab-d568498c7e93.png)

**Comment by JoosepAlviste** [comment]
Interesting... That should return a commentstring if Treesitter and the parser is set up. Does `:TSInstallInfo` also show the `c` parser as installed?

Could you also check what this outputs:

```
:=require('ts_context_commentstring.utils').get_node_at_cursor_start_of_line({})
```

I wouldn't expect to see any `nil`s there.

Also, just to be sure, does the plugin work for other filetypes than C?

Finally, it would be useful to see a minimal config where the issue can be reproduced, just to make sure that no other custom config is affecting the set up. There's a minimal config here: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/18#issuecomment-886105815

**Comment by UtkarshVerma** [comment]
I get this as the output:

```
:=require('ts_context_commentstring.utils').get_node_at_cursor_start_of_line({})
<userdata 1>
{
  _callbacks = {
    bytes = { <function 1>, <function 2> },
    changedtree = { <function 3>, <function 4> },
    child_added = {},
    child_removed = {},
    detach = { <function 5> }
  },
  _children = {
    cpp = {
      _callbacks = {
        bytes = {},
        changedtree = {},
        child_added = {},
        child_removed = {},
        detach = {}
      },
      _children = {},
      _has_regions = true,
      _injection_query = <1>{
        captures = <2>{ "cpp", "comment", "language", "content" },
        info = {
          captures = <table 2>,
          patterns = {}
        },
        query = <userdata 1>,
        <metatable> = <3>{
          __index = <table 3>,
          apply_directives = <function 6>,
          iter_captures = <function 7>,
          iter_matches = <function 8>,
          match_preds = <function 9>
        }
      },
      _lang = "cpp",
      _opts = <4>{},
      _parser = <userdata 2>,
      _regions = { { { 41, 16, 974, 41, 18, 976 } }, { { 42, 15, 992, 42, 18, 995 } }, { { 44, 23, 1020, 44, 26, 1023 } }, { { 153, 27, 4263, 153, 31, 4267
} }, { { 159, 29, 4444, 159, 35, 4450 } }, { { 161, 28, 4480, 161, 38, 4490 } }, { { 162, 28, 4519, 162, 38, 4529 } }, { { 163, 28, 4558, 163, 38, 4568 } }
},
      _source = 1,
      _trees = { <userdata 3>, <userdata 4>, <userdata 5>, <userdata 6>, <userdata 7>, <userdata 8>, <userdata 9>, <userdata 10> },
      _valid = true,
      <metatable> = <5>{
        __index = <table 5>,
        _do_callback = <function 10>,
        _edit = <function 11>,
        _get_injection = <function 12>,
        _get_injection_deprecated = <function 13>,
        _get_injections = <function 14>,
        _iter_regions = <function 15>,
        _log = <function 16>,
        _on_bytes = <function 17>,
        _on_detach = <function 18>,
        _on_reload = <function 19>,
        add_child = <function 20>,
        children = <function 21>,
        contains = <function 22>,
        destroy = <function 23>,
        for_each_child = <function 24>,
        for_each_tree = <function 25>,
        included_regions = <function 26>,
        invalidate = <function 27>,
        is_valid = <function 28>,
        lang = <function 29>,
        language_for_range = <function 30>,
        named_node_for_range = <function 31>,
        new = <function 32>,
        parse = <function 33>,
        register_cbs = <function 34>,
        remove_child = <function 35>,
        set_included_regions = <function 36>,
        source = <function 37>,
        tree_for_range = <function 38>,
        trees = <function 39>
      }
    }
  },
  _injection_query = <table 1>,
  _lang = "cpp",
  _opts = <table 4>,
  _parser = <userdata 11>,
  _source = 1,
  _trees = { <userdata 12> },
  _valid = true,
  <metatable> = <table 5>
}
```

**Comment by UtkarshVerma** [comment]
I think this was probably due to wrong initialization ordering between nvim-treesitter and ts-context-commentstring. I specified ts-context-commentstring as a dependency for treesitter and now the config is picked up.

**Comment by JoosepAlviste** [comment]
That is good to hear because I wasn't sure what was going on and was running out of ideas :D

Glad it got fixed!

**Comment by mortezadadgar** [comment]
> Hey @UtkarshVerma! Do you have the C Treesitter parser installed? If you're using Treesitter in C files, then I wouldn't expect `after/plugin/c.vim` to work since this plugin should set it.
> 
> I tried this out myself by installing the C parser: `:TSInstall c` and configuring the `commentstring`:
> 
> ```lua
> context_commentstring = {
>   enable = true,
>   enable_autocmd = false,
>   config = {
>     c = '// test %s',
>   },
> },
> ```
> 
> Then, commenting seems to use the correct `commentstring`:
> Screen.Recording.2023-04-12.at.08.09.03.mov
> 
> I'm using Comment.nvim though, but I wouldn't expect there to be any big differences from that.
> 
> To debug this further, could you show what `:=require('ts_context_commentstring.internal').calculate_commentstring()` outputs in C files?

sorry for bringing it up in a closed issue, but what is changing `commentstring` for c? I can't find any reference in treesitter source code or here
saying this because it's so annoying as the default vim config uses `/* %s */`
