### ISSUE TITLE
 failed to install

### ISSUE THREAD

**Issue by kamalkech** [JoosepAlviste/nvim-ts-context-commentstring#64]
- NVIM v0.9.0
- System: Mac
![Screenshot 2023-04-17 at 02 29 04](https://user-images.githubusercontent.com/1313428/232364028-8d65b00c-8426-4634-8589-28d240f40d01.png)

**Comment by JoosepAlviste** [comment]
Hey! It's a bit difficult to diagnose this without any extra information.

I think that Packer can show the installation output if you press some key on the line. Maybe enter or `d`? Could you show the output for that?

If there's nothing useful there, could you try a minimal config to see if there's some issue with your configuration? https://github.com/JoosepAlviste/nvim-ts-context-commentstring/blob/8640672107be3933f4c2138dbfa2f5732180cfec/utils/minimal_vimrc.vim

**Comment by JoosepAlviste** [comment]
Interesting, looks like there new Vim docs have a duplicate tag. I pushed a fixed to `main`, can you try it again and see if that fixes your issue @rokonio?

The vim docs were merged earlier today though, so I wouldn't expect this to be the same issue that @kamalkech is having. But it *should* fix the duplicate docs issue 🤞

**Comment by rokonio** [comment]
This fixed my issue, thanks

**Comment by JoosepAlviste** [comment]
Glad to hear! I'll close this issue then, feel free to re-open if there is still a problem with installing.
