### ISSUE TITLE
module 'ts-context-com mentstring.integrations.comment_nvim' not found:

### ISSUE THREAD

**Issue by Zeddnyx** [JoosepAlviste/nvim-ts-context-commentstring#65]
### Minimal reproducible full config

```lua
{
    "nvim-treesitter/nvim-treesitter",
     lazy = true,
     event = "BufRead",
     dependencies = {
       "p00f/nvim-ts-rainbow",
       "JoosepAlviste/nvim-ts-context-commentstring",
     },
     config = function()
      require("configs.ui.treesitter")
   end,
},
{
  "numToStr/Comment.nvim",
   keys = { { "gc", mode = { "n", "v" }, "gcc"}, { "gb", mode = { "n", "v" } } },
   lazy = true,
  config = function()
    require("Comment").setup {
       pre_hook = require("ts-context-commentstring.integrations.comment_nvim").create_pre_hook(),
   }
end,
},
```

### Description

how to correct setup ?

### Steps to reproduce

try goggle it and not any match of my issue

### Expected behavior

i just wanna comment jsx file 

### Actual behavior

.

**Comment by JoosepAlviste** [comment]
Hey @Zeddnyx! It looks like you have a typo in the `pre_hook` configuration. The require should use underscores for the plugin name, not dashes:

```lua
pre_hook = require('ts_context_commentstring.integrations.comment_nvim').create_pre_hook(),
```

Are there dashes used in some docs or was this just a typo? It looks to be correct in the integrations wiki page: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/wiki/Integrations#commentnvim

**Comment by Zeddnyx** [comment]
Lol just typo 🤣
Thanks
