### ISSUE TITLE
mini.comment integration pre hook - require("ts_context_commentstring.internal").update_commentstring() requires 1 argument

### ISSUE THREAD

**Issue by krishna-bala** [JoosepAlviste/nvim-ts-context-commentstring#68]
I'm trying to set the pre hook for `mini.comment` per the instructions on the wiki for [Integrations](https://github.com/JoosepAlviste/nvim-ts-context-commentstring/wiki/Integrations#minicomment). My LSP is telling me that `require("ts_context_commentstring.internal").update_commentstring()` 

> requires 1 argument(s) but instead it is receiving 0.

Ignoring that warning doesn't cause any error messages when loading my plugins, but it does not seem to update the comment string as expected (it leaves it unchanged).

I'm using the [LazyVim](https://www.lazyvim.org/plugins) distribution, so it may be some plugin configuration issue on my end. But I just wanted to double check that wiki Integration page is still correct for `mini.comment` before asking for help on the LazyVim discussion board.

**Comment by JoosepAlviste** [comment]
Hey @krishna-bala! The configuration looks correct to me. I haven't used LazyVim though, so I'm not sure if there are any special steps that need to be taken.

`update_commentstring()` does accept 1 argument with extra options, but it isn't required. I think that we should update the function docs to set it as optional. The code docs could be improved in general.

Here are some questions and things to try:

1. What file type are you trying this out in?
2. If you manually call `:=require('ts_context_commentstring.internal').calculate_commentstring()`, then does that output the correct commentstring?

**Comment by victornswd** [comment]
Not really sure if this is helpful for this situation, but I was having issues with `mini.comment` in the past weeks as well. It changed to commentstring from tree-sitter which caused some issues with some filetypes. I opened an issue on this and I got a recommended a new way of setting up `nvim-ts-context-commentstring`: https://github.com/echasnovski/mini.nvim/issues/342

**Comment by JoosepAlviste** [comment]
Thanks for letting me know, @victornswd! I've updated the integration instructions in the wiki: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/wiki/Integrations#minicomment

Hopefully this solves the issue. Feel free to re-open if there are still problems with this.
