### ISSUE TITLE
Does this work well when nvim-treesitter 1.0 is out?

### ISSUE THREAD

**Issue by towry** [JoosepAlviste/nvim-ts-context-commentstring#72]
### Minimal reproducible full config

https://github.com/nvim-treesitter/nvim-treesitter/tree/main

### Description

https://github.com/nvim-treesitter/nvim-treesitter/issues/4767

### Steps to reproduce

None

### Expected behavior

None

### Actual behavior

None

### Additional context

None

**Comment by towry** [comment]
Seems not.

**Comment by JoosepAlviste** [comment]
Hey! I haven't tested this on nvim-treesitter 1.0 yet. I'll try to take some time at some point to go through the changes and to see how difficult it would be to support it.

Thanks for bringing this to my attention!

**Comment by Slotos** [comment]
Primarily this boils down to:

- this plugin maintaining its own initialization and config

    `define_modules` is gone, `nvim-treesitter-context` is a recommended example (https://github.com/nvim-treesitter/nvim-treesitter-context/blob/master/lua/treesitter-context.lua#L787). `nvim-ts-autotag` could serve a simpler example.

    `configs.get_module` is gone, this plugin needs to handle its own configuration.

- `parsers` is mostly gone in favour of code treesitter functions

    [`vim.treesitter.get_parser()`](https://neovim.io/doc/user/treesitter.html#vim.treesitter.get_parser()) can replace the use of `parsers.has_parser` and `parsers.get_parser` both.

And I believe that would be mostly it.

**Comment by JoosepAlviste** [comment]
Hey @towry! There is now a `setup` function exported from this module, which can be used with `nvim-treesitter` >= 1.0. Please see the readme for details and try it out!

**Comment by towry** [comment]
Hi, thanks for the great work, just test it with nvim-treesitter#main, works well 👍
