### ISSUE TITLE
Confused on how to integrate this with lua inside init.vim

### ISSUE THREAD

**Issue by KarlWithK** [JoosepAlviste/nvim-ts-context-commentstring#8]
Hello, so for some capability issues I have in my init.vim snippets like this:
```vim
function! FilePath() abort
    " stuff
endfunction

lua <<EOF
-- more stuff
EOF
```
However, whenever I try to comment stuff inside the lua snippets I get the commentstring to still be `\"%s`. Is there anyway, I can use this plugin to handle this situation. I'm frankly a bit confused.

**Comment by JoosepAlviste** [comment]
Hey @KarlWithK! There is no officially supported vimscript treesitter parser, but this plugin is specifically meant to be used in languages that are supported by treesitter.

There is this issue open in the nvim-treesitter repo though: https://github.com/nvim-treesitter/nvim-treesitter/issues/1187, are you using the experimental vimscript parser mentioned there?
