### ISSUE TITLE
Error in javascript file

### ISSUE THREAD

**Issue by elkowar** [JoosepAlviste/nvim-ts-context-commentstring#9]
no matter where I am in a javascript file, the following error constantly pops up:
```
Error detected while processing CursorHold Autocommands for "<buffer=48>":
E5108: Error executing lua ...-commentstring/lua/ts_context_commentstring/internal.lua:72: attempt to index local 'language_tree' (a nil value)
```

**Comment by JoosepAlviste** [comment]
Hey! That seems strange.

Do you have the latest Neovim nightly version? Language tree was added to Neovim a few months ago, so if you have recently updated Neovim, then that shouldn't be a problem.

Another thing to check is if you have the `javascript` treesitter parser installed (`:TSInstall javascript`).

If none of those are the case, then could you share some minimal `init.vim` to reproduce this?

---

I could also add an extra `if` statement to check if the `language_tree` is set in front of `lua/ts_context_commentstring/internal.lua:72`. It would avoid the error, but might effectively disable the plugin for you.

**Comment by JoosepAlviste** [comment]
Just to let you know, I added an extra check for this so you should no longer get that error, but `commentstring` calculation won't work in that case. Maybe the issue will be fixed by one of the ideas in the previous comment.

Anyways, let me know how it goes!

**Comment by JoosepAlviste** [comment]
I will close this issue for now, if the issue still persists, then feel free to re-open.
